import type { SubscriptionTool } from '~/types/calculator';

export const SUBSCRIPTION_TOOLS: SubscriptionTool[] = [
  // Creative & Marketing
  {
    id: 'adobe_cc_all',
    name: 'calculator.tools.adobe_cc_all.name',
    price: 69.00,
    currency: 'EUR',
    category: 'creative',
    riskLevel: 'medium',
    conflictId: 'canva_pro',
    conflictMessage: 'calculator.tools.adobe_cc_all.conflictMessage',
    icon: 'adobe',
  },
  {
    id: 'adobe_cc_single',
    name: 'calculator.tools.adobe_cc_single.name',
    price: 33.49,
    currency: 'EUR',
    category: 'creative',
    riskLevel: 'medium',
    icon: 'adobe',
  },
  {
    id: 'canva_pro',
    name: 'calculator.tools.canva_pro.name',
    price: 49.99,
    currency: 'PLN',
    category: 'creative',
    riskLevel: 'very-high',
    conflictId: 'adobe_cc_all',
    conflictMessage: 'calculator.tools.canva_pro.conflictMessage',
    icon: 'canva',
  },
  {
    id: 'canva_team',
    name: 'calculator.tools.canva_team.name',
    price: 145.00,
    currency: 'PLN',
    category: 'creative',
    riskLevel: 'high',
    icon: 'canva',
  },
  {
    id: 'figma_pro',
    name: 'calculator.tools.figma_pro.name',
    price: 15.00,
    currency: 'USD',
    category: 'creative',
    riskLevel: 'medium',
    icon: 'figma',
  },
  {
    id: 'figma_org',
    name: 'calculator.tools.figma_org.name',
    price: 45.00,
    currency: 'USD',
    category: 'creative',
    riskLevel: 'high',
    icon: 'figma',
  },
  {
    id: 'ahrefs_lite',
    name: 'calculator.tools.ahrefs_lite.name',
    price: 129.00,
    currency: 'USD',
    category: 'creative',
    riskLevel: 'very-high',
    conflictId: 'semrush_pro',
    conflictMessage: 'calculator.tools.ahrefs_lite.conflictMessage',
    icon: 'ahrefs',
  },
  {
    id: 'semrush_pro',
    name: 'calculator.tools.semrush_pro.name',
    price: 139.95,
    currency: 'USD',
    category: 'creative',
    riskLevel: 'very-high',
    conflictId: 'ahrefs_lite',
    conflictMessage: 'calculator.tools.semrush_pro.conflictMessage',
    icon: 'semrush',
  },
  {
    id: 'chatgpt_plus',
    name: 'calculator.tools.chatgpt_plus.name',
    price: 110.00,
    currency: 'PLN',
    category: 'creative',
    riskLevel: 'medium',
    icon: 'openai',
  },
  {
    id: 'mailchimp_standard',
    name: 'calculator.tools.mailchimp_standard.name',
    price: 17.18,
    currency: 'EUR',
    category: 'creative',
    riskLevel: 'medium',
    icon: 'mailchimp',
  },

  // Infrastructure & Communication
  {
    id: 'm365_personal',
    name: 'calculator.tools.m365_personal.name',
    price: 42.99,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'low',
    conflictId: 'google_workspace_starter',
    conflictMessage: 'calculator.tools.m365_personal.conflictMessage',
    icon: 'microsoft',
  },
  {
    id: 'm365_premium',
    name: 'calculator.tools.m365_premium.name',
    price: 97.99,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'low',
    conflictId: 'google_workspace_std',
    conflictMessage: 'calculator.tools.m365_premium.conflictMessage',
    icon: 'microsoft',
  },
  {
    id: 'google_workspace_starter',
    name: 'calculator.tools.google_workspace_starter.name',
    price: 27.00,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'low',
    conflictId: 'm365_personal',
    conflictMessage: 'calculator.tools.google_workspace_starter.conflictMessage',
    icon: 'google',
  },
  {
    id: 'google_workspace_std',
    name: 'calculator.tools.google_workspace_std.name',
    price: 54.00,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'low',
    conflictId: 'm365_premium',
    conflictMessage: 'calculator.tools.google_workspace_std.conflictMessage',
    icon: 'google',
  },
  {
    id: 'dropbox_plus',
    name: 'calculator.tools.dropbox_plus.name',
    price: 11.99,
    currency: 'EUR',
    category: 'infrastructure',
    riskLevel: 'high',
    conflictId: 'm365_premium',
    conflictMessage: 'calculator.tools.dropbox_plus.conflictMessage',
    icon: 'dropbox',
  },
  {
    id: 'google_one',
    name: 'calculator.tools.google_one.name',
    price: 49.99,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'medium',
    icon: 'google',
  },
  {
    id: 'icloud_plus',
    name: 'calculator.tools.icloud_plus.name',
    price: 59.99,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'medium',
    icon: 'icloud',
  },
  {
    id: 'wetransfer_pro',
    name: 'calculator.tools.wetransfer_pro.name',
    price: 13.00,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'high',
    conflictId: 'google_workspace_std',
    conflictMessage: 'calculator.tools.wetransfer_pro.conflictMessage',
    icon: 'wetransfer',
  },
  {
    id: 'zoom_pro',
    name: 'calculator.tools.zoom_pro.name',
    price: 15.00,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'high',
    conflictId: 'm365_premium',
    conflictMessage: 'calculator.tools.zoom_pro.conflictMessage',
    icon: 'zoom',
  },
  {
    id: 'slack_pro',
    name: 'calculator.tools.slack_pro.name',
    price: 8.75,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'medium',
    conflictId: 'm365_premium',
    conflictMessage: 'calculator.tools.slack_pro.conflictMessage',
    icon: 'slack',
  },
  {
    id: 'asana_starter',
    name: 'calculator.tools.asana_starter.name',
    price: 13.49,
    currency: 'EUR',
    category: 'infrastructure',
    riskLevel: 'medium',
    icon: 'asana',
  },
  {
    id: 'trello_std',
    name: 'calculator.tools.trello_std.name',
    price: 6.00,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'medium',
    conflictId: 'monday_std',
    conflictMessage: 'calculator.tools.trello_std.conflictMessage',
    icon: 'trello',
  },

  {
    id: 'notion_plus',
    name: 'calculator.tools.notion_plus.name',
    price: 12.00,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'medium',
    conflictId: 'trello_std',
    conflictMessage: 'calculator.tools.notion_plus.conflictMessage',
    icon: 'notion',
  },
  {
    id: 'nordvpn',
    name: 'calculator.tools.nordvpn.name',
    price: 13.00,
    currency: 'EUR',
    category: 'infrastructure',
    riskLevel: 'medium',
    icon: 'nordvpn',
  },
  {
    id: '1password',
    name: 'calculator.tools.1password.name',
    price: 7.99,
    currency: 'USD',
    category: 'infrastructure',
    riskLevel: 'low',
    icon: '1password',
  },
  {
    id: 'norton_360',
    name: 'calculator.tools.norton_360.name',
    price: 12.00,
    currency: 'PLN',
    category: 'infrastructure',
    riskLevel: 'medium',
    icon: 'norton',
  },

  // Lifestyle & Entertainment
  {
    id: 'netflix_prem',
    name: 'calculator.tools.netflix_prem.name',
    price: 67.00,
    currency: 'PLN',
    category: 'lifestyle',
    icon: 'netflix',
  },
  {
    id: 'disney_plus',
    name: 'calculator.tools.disney_plus.name',
    price: 49.99,
    currency: 'PLN',
    category: 'lifestyle',
    icon: 'disney',
  },
  {
    id: 'hbo_max',
    name: 'calculator.tools.hbo_max.name',
    price: 29.99,
    currency: 'PLN',
    category: 'lifestyle',
    icon: 'hbo',
  },
  {
    id: 'spotify_prem',
    name: 'calculator.tools.spotify_prem.name',
    price: 19.99,
    currency: 'PLN',
    category: 'lifestyle',
    conflictId: 'youtube_prem',
    conflictMessage: 'calculator.tools.spotify_prem.conflictMessage',
    icon: 'spotify',
  },
  {
    id: 'youtube_prem',
    name: 'calculator.tools.youtube_prem.name',
    price: 25.99,
    currency: 'PLN',
    category: 'lifestyle',
    icon: 'youtube',
  },
  {
    id: 'multisport',
    name: 'calculator.tools.multisport.name',
    price: 180.00,
    currency: 'PLN',
    category: 'lifestyle',
  },

  {
    id: 'legimi',
    name: 'calculator.tools.legimi.name',
    price: 49.99,
    currency: 'PLN',
    category: 'lifestyle',
  },

  // Development & IT
  {
    id: 'jetbrains_all',
    name: 'calculator.tools.jetbrains_all.name',
    price: 28.90,
    currency: 'EUR',
    category: 'development',
    riskLevel: 'medium',
    icon: 'jetbrains',
  },
  {
    id: 'github_team',
    name: 'calculator.tools.github_team.name',
    price: 4.00,
    currency: 'USD',
    category: 'development',
    riskLevel: 'low',
    icon: 'github',
  },
  {
    id: 'jira_standard',
    name: 'calculator.tools.jira_standard.name',
    price: 8.15,
    currency: 'USD',
    category: 'development',
    riskLevel: 'medium',
    icon: 'jira',
  },
  {
    id: 'digitalocean',
    name: 'calculator.tools.digitalocean.name',
    price: 24.00,
    currency: 'USD',
    category: 'development',
    riskLevel: 'low',
    icon: 'digitalocean',
  },
  {
    id: 'vercel_pro',
    name: 'calculator.tools.vercel_pro.name',
    price: 20.00,
    currency: 'USD',
    category: 'development',
    riskLevel: 'medium',
    icon: 'vercel',
  },
  {
    id: 'docker_pro',
    name: 'calculator.tools.docker_pro.name',
    price: 9.00,
    currency: 'USD',
    category: 'development',
    riskLevel: 'medium',
    icon: 'docker',
  },
  {
    id: 'gitlab_premium',
    name: 'calculator.tools.gitlab_premium.name',
    price: 29.00,
    currency: 'USD',
    category: 'development',
    riskLevel: 'medium',
    icon: 'gitlab',
    conflictId: 'github_team',
    conflictMessage: 'calculator.tools.gitlab_premium.conflictMessage',
  },

  // Sales & CRM
  {
    id: 'linkedin_sales',
    name: 'calculator.tools.linkedin_sales.name',
    price: 99.99,
    currency: 'USD',
    category: 'sales',
    riskLevel: 'high',
    icon: 'linkedin',
  },
  {
    id: 'hubspot_sales',
    name: 'calculator.tools.hubspot_sales.name',
    price: 50.00,
    currency: 'USD',
    category: 'sales',
    riskLevel: 'medium',
    icon: 'hubspot',
    conflictId: 'salesforce_essentials',
    conflictMessage: 'calculator.tools.hubspot_sales.conflictMessage',
  },
  {
    id: 'salesforce_essentials',
    name: 'calculator.tools.salesforce_essentials.name',
    price: 25.00,
    currency: 'EUR',
    category: 'sales',
    riskLevel: 'medium',
    icon: 'salesforce',
    conflictId: 'hubspot_sales',
    conflictMessage: 'calculator.tools.salesforce_essentials.conflictMessage',
  },
  {
    id: 'pipedrive_pro',
    name: 'calculator.tools.pipedrive_pro.name',
    price: 49.00,
    currency: 'EUR',
    category: 'sales',
    riskLevel: 'medium',
  },
  {
    id: 'calendly_pro',
    name: 'calculator.tools.calendly_pro.name',
    price: 12.00,
    currency: 'USD',
    category: 'sales',
    riskLevel: 'medium',
    icon: 'calendly',
  },

  // E-commerce
  {
    id: 'shopify_basic',
    name: 'calculator.tools.shopify_basic.name',
    price: 36.00,
    currency: 'USD',
    category: 'ecommerce',
    riskLevel: 'low',
    icon: 'shopify',
  },
  {
    id: 'allegro_smart',
    name: 'calculator.tools.allegro_smart.name',
    price: 49.00,
    currency: 'PLN',
    category: 'ecommerce',
    riskLevel: 'low',
    icon: 'allegro',
  },

  {
    id: 'woocommerce_hosting',
    name: 'calculator.tools.woocommerce_hosting.name',
    price: 79.00,
    currency: 'PLN',
    category: 'ecommerce',
    riskLevel: 'low',
    icon: 'woocommerce',
  },
  {
    id: 'prestashop_hosting',
    name: 'calculator.tools.prestashop_hosting.name',
    price: 99.00,
    currency: 'PLN',
    category: 'ecommerce',
    riskLevel: 'low',
    icon: 'prestashop',
  },

];

