name: Deploy to SSH Server
on:
  push:
    branches:
      - master
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Log in to SSH server
          uses: appleboy/ssh-action@v1.0.3
          with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                password: ${{ secrets.SSH_PASSWORD }}
                script: |
                    cd personal-website
                    git pull
                    docker compose down
                    docker compose up -d --build
