name: ftp-action
on: push
jobs:
  ftp:
    name: FTP Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Upload ftp
      uses: sebastianpopp/ftp-action@releases/v2
      with:
        # FTP host
        host: ${{ secrets.FTP_HOST }}
        # FTP user
        user: ${{ secrets.FTP_LOGIN }}
        # FTP password
        password: ${{ secrets.FTP_PASSWORD }}
        # Force SSL encryption
        forceSsl: true
        # Local directory
        localDir: dist # optional, default is .
        # Remote directory
        remoteDir: /home/slawomy/www # optional, default is .
            
