name: ftp-action
on: push
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: dist
        key: ${{ runner.os }}-dist
  deploy:
    name: FTP Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: dist
        key: ${{ runner.os }}-dist
    - name: Upload ftp
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        # FTP host
        server: ${{ secrets.FTP_HOST }}
        # FTP user
        username: ${{ secrets.FTP_LOGIN }}
        # FTP password
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        port: 22
        # Local directory
        local-dir: /home/runner/work/personal-website/personal-website/dist/ # optional, default is .
        # Remote directory
        server-dir: /home/slawomy/www/ # optional, default is .
            
