name: ftp-action
on: push
jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install
    - name: Build
      run: npm run build
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: dist
        key: ${{ github.run_id }}-${{ github.run_attempt }}
  deploy:
    name: FTP Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Cache build
      uses: actions/cache@v2
      with:
        path: dist
        key: ${{ github.run_id }}-${{ github.run_attempt }}
    - name: Upload ftp
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        # FTP host
        server: ${{ secrets.FTP_HOST }}
        # FTP user
        username: ${{ secrets.FTP_LOGIN }}
        # FTP password
        password: ${{ secrets.FTP_PASSWORD }}
        sftp_only: true
        port: 22
        # Local directory
        local_path: dist/* # optional, default is .
        # Remote directory
        remote_path: /home/slawomy/www/
            
