name: PR Agent
on:
  push:
    branches:
      - pr-test
  issue_comment:
jobs:
  pr_agent_job:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: PR Agent action step
        uses: qodo-ai/pr-agent@main
        env:
          OPENAI_API_BASE: "https://openrouter.ai/api/v1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENROUTER__KEY: ${{ secrets.OPENROUTER_API_KEY }}
          # Set the model to work with OpenRouter
          config.model: "openrouter/qwen/qwen-3-coder-free"
          config.fallback_models: '["openrouter/moonshotai/kimi-k2:free"]'
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          OPENROUTER_BASE_URL: "https://openrouter.ai/api/v1"
          # Tool configuration
          github_action_config.auto_review: "true"
          github_action_config.auto_describe: "true"
          github_action_config.auto_improve: "true"